name: Panic Button
version: 5
markdown: redcarpet
pygments: true
permalink: /:categories/:title.html
exclude:
  - .gitignore
  - README.md
  - privatekey.p12
  - Gemfile
  - Gemfile.lock
languages: &languages
  - name: 'English'
    value: 'en'
  - name: 'Espa√±ol'
    value: 'es'

prose:
  rooturl: '_posts'
  siteurl: 'http://teampanicbutton.github.io'
  relativeLinks: 'teampanicbutton.github.io/links.jsonp'
  media: 'media'
  metadata:
    _posts/web:
      - name: "layout"
        field:
          element: "hidden"
      - name: "lang"
        field:
          element: "select"
          label: "Select language"
          placeholder: "English"
          options: *languages
          selected: "en"
      - name: "heading"
        field:
          element: "text"
          label: "Section's heading"
          placeholder: "This is a heading"
      - name: "category"
        field:
          element: "text"
          label: "Option"
          placeholder: "Learn more about this. "
      - name: "section_order"
        field:
          element: "number"
          label: "Section Order"
    _posts/help:
      - name: "layout"
        field:
          element: "hidden"
      - name: "heading"
        field:
          element: "text"
          label: "Post's heading"
          placeholder: "This is a heading"
    _posts/mobile:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "lang"
        field:
          element: "select"
          label: "Select language"
          placeholder: "English"
          options: *languages
          selected: "en"
      - name: "slug"
        field:
          element: "hidden"
          label: "Post's id"
      - name: "type"
        field:
          element: "hidden"
          label: "Post's type - simple, interactive, modal"
      - name: "title"
        field:
          element: "text"
          label: "Section's title"
          placeholder: "This is a title"
      - name: "action"
        field:
          element: "hidden"
          label: "Action"
      - name: "items"
        field:
          element: "hidden"
          label: "Items"
      - name: "success"
        field:
          element: "hidden"
          label: "Success"
      - name: "component"
        field:
          element: "hidden"
          label: "component"
